language: erlang
otp_release:
- 17.4
env:
- RMQ_TAG=v3_5_1 RMQ_VERSION=3.5.x GUN_COMMIT=a752035 GUN_VERSION=0.1.0 BUILD_DIR=$HOME/rabbitmq-public-umbrella
before_install:
- $TRAVIS_BUILD_DIR/travis-umbrella-setup.sh
install:
- sudo apt-get update -qq
- sudo apt-get install -qq -y xsltproc
script: VERSION=$RMQ_VERSION make test
cache:
  apt: true
  directories:
  - $BUILD_DIR
deploy:
  provider: releases
  api_key:
    secure: ZFDjg8FW2tEkIAr87uA9vfB+WZMq30GKwL+ACaajow2mqeCvW5ZGfFzaxuMBCQILE0uNLxM9lLmtw+IYQF/Z7qIGhyJHiEsG24yeHcQJhfbjzizjKr8lYW14zi9XOlX6nmOHyTvhmfqjPZN2eOBF5dPW28kUW3YzCZg2Gi+hMmE=
  file: $TRAVIS_BUILD_DIR/dist/gun-${GUN_VERSION}-rmq${RMQ_VERSION}-git${GUN_COMMIT}.ez
  on:
    tags: true
    repo: gmr/gun-wrapper
